name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Remove .git folder to avoid permission errors
      run: rm -rf .git

    - name: Create SSH key file
      run: |
        echo "$EC2_SSH_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem
      shell: bash

    - name: Deploy files to EC2
      run: |
        scp -i ec2_key.pem -o StrictHostKeyChecking=no -r ./ \
           --exclude '.git' \
           ${EC2_USER}@${EC2_HOST}:/home/ubuntu/podiFY_Transcription

      env:
        EC2_USER: ubuntu
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    - name: SSH into EC2 and restart service
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_PUBLIC_IP} << 'EOF'
        cd /home/ubuntu/podiFY_Transcription
        tmux kill-session -t podifyapp || true
        tmux new -d -s podifyapp "python3 app.py"
        EOF
      env:
        EC2_USER: ubuntu
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
